# Generated by Django 4.1.4 on 2022-12-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_alter_entry_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
